Repository Somil2104/Votify, pull requests merged in 2025-01, with the labels that each got.

#3 #2 issue resolved created figma wireframe for 3 main pages Home, create, join
  README.md
Labels: acwoc, hard

#5 Home Page Programmed #4 + more
  package-lock.json
  votify/assets/create-poll.png
  votify/assets/join-poll.png
  votify/backend/server.js
  votify/frontend/footer.html
  votify/frontend/home.html
  votify/frontend/index.html
  votify/frontend/navbar.html
  votify/frontend/script.js
  votify/frontend/style.css
  votify/frontend/styles/footer.css
  votify/frontend/styles/main.css
  votify/frontend/styles/navbar.css
  votify/frontend/styles/reset.css
  votify/frontend/styles/style.css
  votify/package.json
Labels: acwoc, hard

#8 #6 Completed Dark mode and responsive sidebar
  votify/frontend/footer.html
  votify/frontend/home.html
  votify/frontend/navbar.html
  votify/frontend/script.js
  votify/frontend/sidebar.html
  votify/frontend/styles/footer.css
  votify/frontend/styles/main.css
  votify/frontend/styles/navbar.css
  votify/frontend/styles/reset.css
  votify/frontend/styles/sidebar.css
  votify/frontend/styles/style.css
  votify/frontend/styles/theme.css
Labels: acwoc, hard

#9 Fully Setup the Backend Server and the Fix of File Handling
  votify/.gitignore
  votify/Setup_Instructions.md
  votify/backend/server.js
  votify/frontend/assets/create-poll.png
  votify/frontend/assets/join-poll.png
  votify/frontend/home.html
  votify/frontend/navbar.html
Labels: acwoc, medium

#17 #12 completed
  votify/frontend/assets/lottiePoll1.json
  votify/frontend/home.html
  votify/frontend/join.html
  votify/frontend/navbar.html
  votify/frontend/styles/footer.css
  votify/frontend/styles/join.css
  votify/frontend/styles/theme.css
Labels: acwoc, hard

#21 Adding Deployment Feature in this Project
  votify/api/index.js
  votify/backend/server.js
  votify/package.json
  votify/vercel.json
Labels: acwoc, medium

#22 Updated vercel.json to use server.js only for Deployment on Vercel
  votify/api/index.js
  votify/vercel.json
Labels: acwoc, easy

#24 #19 Completed
  README.md
Labels: acwoc, medium

#25 Implemented the New Theme Switch Toggle
  votify/frontend/home.html
  votify/frontend/join.html
  votify/frontend/navbar.html
  votify/frontend/script.js
  votify/frontend/sidebar.html
  votify/frontend/styles/navbar.css
  votify/frontend/styles/sidebar.css
  votify/frontend/styles/theme.css
Labels: acwoc, medium

#28 Team page added, missing on clicks set and new sidebar updated
  votify/frontend/assets/CoderYUI.png
  votify/frontend/assets/Harshit-Maurya838.jpg
  votify/frontend/assets/Somil2104.jpg
  votify/frontend/assets/TeamAnimation.json
  votify/frontend/assets/amaansyed27.png
  votify/frontend/assets/anumi1999.png
  votify/frontend/assets/css.png
  votify/frontend/assets/html.png
  votify/frontend/assets/js.png
  votify/frontend/assets/node.png
  votify/frontend/assets/shreyash3087.png
  votify/frontend/assets/vercel.png
  votify/frontend/home.html
  votify/frontend/join.html
  votify/frontend/navbar.html
  votify/frontend/styles/team.css
  votify/frontend/styles/theme.css
  votify/frontend/team.html
Labels: acwoc, hard

#32 #27 Completed Help page added
  votify/frontend/help.html
  votify/frontend/navbar.html
  votify/frontend/script.js
  votify/frontend/styles/help.css
  votify/frontend/styles/theme.css
Labels: acwoc, hard

#33 Adding some changes and fixing the bugs
  votify/frontend/home.html
  votify/frontend/styles/main.css
Labels: acwoc, hard

#36 fix: Resolved footer issues and broken navigation links
  votify/frontend/footer.html
  votify/frontend/home.html
  votify/frontend/script.js
  votify/frontend/styles/footer.css
Labels: acwoc, easy

#39 Update README.md with pages designed and console design
  README.md
Labels: acwoc, hard

#40 Home Page updated
  votify/frontend/home.html
  votify/frontend/script.js
  votify/frontend/styles/main.css
Labels: acwoc, medium

#41 Create poll page UI with full functionlity
  votify/backend/server.js
  votify/frontend/create.html
  votify/frontend/home.html
  votify/frontend/navbar.html
  votify/frontend/styles/create.css
  votify/package.json
Labels: acwoc, hard

#45 Made Change to the Navbar
  votify/frontend/navbar.html
Labels: acwoc, hard

#48 Teams Page UI Enhanced
  votify/frontend/team.html
Labels: acwoc, hard
