Repository Somil2104/Votify, pull requests merged in 2025-02, with the labels that each got.

#52 Enhancement of the help page
  votify/frontend/help.html
  votify/frontend/styles/help.css
Labels: acwoc, hard

#53 Fixed Create Poll Button
  votify/frontend/navbar.html
Labels: acwoc, easy

#54 Made the look and feel better and aded new features
  votify/frontend/footer.html
Labels: acwoc, medium

#56 Added Issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/general_issue.md
Labels: acwoc, easy

#59 Added Scroll To Top functionality
  votify/frontend/script.js
  votify/frontend/styles/main.css
Labels: acwoc, medium

#63 Updated twitter icon to X
  votify/frontend/footer.html
  votify/frontend/home.html
  votify/frontend/styles/footer.css
  votify/frontend/team.html
Labels: acwoc, easy
